services:
  - type: web
    name: proffbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PUSHOVER_TOKEN
        sync: false
      - key: PUSHOVER_USER
        sync: false
